import { test, expect } from "@playwright/test";
test("Structure resizes, folds, restores and persists while component slot fields stay usable", async ({ page, baseURL }) => {
  const open = async () => {
    await page.goto(`${baseURL}/#repo=501&branch=main&file=index.html`);
    await expect(page.locator("#current-page")).toHaveAttribute("data-path", "index.html");
    await expect(page.frameLocator(".native-preview-frame").locator(".hero h1")).toBeVisible();
    const section = page.getByRole('treeitem', {name:'Section',exact:true});
    if(await section.getAttribute('aria-expanded')==='false')await section.locator('.page-structure__toggle').click();
    const instance = page.getByRole('treeitem', {name:/^Project card Reusable cards$/});
    await instance.locator(".page-structure__label").click();
    if (await instance.getAttribute('aria-expanded') === 'false') await instance.locator('.page-structure__toggle').click();
    await page.locator('.page-structure__slot-badge').filter({hasText:/^Title$/}).first().press('Enter');
    await expect(page.locator('#structure').getByRole('textbox',{name:'Title: Text',exact:true})).toHaveValue('Reusable cards');
  };
  await open();
  const sidebar = page.locator('#structure-sidebar');
  const handle = page.getByRole("separator", { name: "Resize page structure sidebar" });
  await expect(handle).toBeVisible();
  const before = (await sidebar.boundingBox())!.width;
  const box = (await handle.boundingBox())!;
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 80, box.y + box.height / 2, { steps: 5 }); await page.mouse.up();
  const resized = (await sidebar.boundingBox())!.width;
  expect(resized).toBeGreaterThan(before);
  await handle.press("Enter");
  await expect(handle).toHaveAttribute("aria-valuenow", "0");
  await expect(page.locator('#structure')).toBeHidden();
  await expect(handle).toBeVisible();
  await handle.press("Enter");
  expect((await sidebar.boundingBox())!.width).toBe(resized);
  await open();
  expect((await sidebar.boundingBox())!.width).toBe(resized);
  await handle.press("ArrowLeft");
  expect((await sidebar.boundingBox())!.width).toBeLessThan(resized);
  const title = page.locator('#structure').getByRole('textbox',{name:'Title: Text',exact:true});
  await title.fill('Resized Structure stays editable'); await title.press('Enter');
  await expect(page.frameLocator('.native-preview-frame').locator('project-card [slot=title]').first()).toHaveText('Resized Structure stays editable');
  await page.frameLocator(".native-preview-frame").locator("project-card [slot=title]").first().click();
  const selected = page.locator('#structure [data-slot=title][aria-selected=true]').first();
  await expect(selected).toBeVisible();
  expect(await selected.evaluate(element => getComputedStyle(element).boxShadow)).toBe("none");
  await page.getByRole("tree", {name:"Page structure"}).getByRole("treeitem", {name:"Section A native browser preview", exact:true}).locator(".page-structure__label").click();
  await expect(page.getByRole('tree',{name:'Page structure'})).toBeVisible();
  await expect(handle).toBeVisible();
  await expect(page.getByRole('treeitem',{name:'Section A native browser preview',exact:true})).toHaveAttribute('aria-selected','true');
});
