import {expect,test} from '@playwright/test';
test.beforeEach(async({page,baseURL})=>{await page.goto(new URL('/tests/slot-ghosts/fixture.html',baseURL!).href);});
// Native Structure baseline: rich and simple slot assignments are real treeitems in source order; slot fields open only on an explicit pencil, F2 or badge.
async function harness(page:any) {
 await page.evaluate(async()=>{
  const componentPath='/src/page-builder/components.ts',structurePath='/src/components/page-structure.ts';
  const editsPath='/src/guarded-edit.ts',memoryPath='/tests/fakes/memory-workspace.ts';const {createGuardedEdits}=await import(editsPath),{createMemoryWorkspace}=await import(memoryPath);const {createComponentTools}=await import(componentPath),{createPageStructure}=await import(structurePath);
  document.body.replaceChildren();const host=document.createElement('aside');host.style.cssText='width:320px;height:700px';document.body.append(host);
  const state:any=(window as any).slotHarness={source:'<project-card id="card" class="caf&eacute; cards" title="A &amp; B" data-note="old"><span slot="title">Original</span><div slot="body" id="rich"><button><span>Act</span></button><p>Paragraph</p></div><img slot="image" src="/old.png" alt="Old"><a slot="cta" href="/before">Go</a><div slot="unknown">Keep unknown</div></project-card>',template:'<article><slot name=body></slot><h2><slot name="title">Title</slot></h2><slot name="image"><img src="/fallback.png" alt="Fallback"></slot><slot name="cta"><a href="/fallback">Fallback link</a></slot><div><slot name="optional"></slot></div></article>',revision:'A',model:1,version:0,closed:0,movesTo:[],moves:[],selected:[],opened:[],notices:[]};
  const templatePath='components/project-card.html';let current='index.html';let sidebar:any;
  const item=(tag:string,node:number[],text='',slot='',children:any[]=[])=>({tag,node,text,slot,heading:'',children});
  const update=()=>{
   const doc=new DOMParser().parseFromString(state.source,'text/html');
   const walk=(el:Element,node:number[]):any=>item(el.localName,node,el.textContent??'',el.getAttribute('slot')??'',[...el.children].map((child,index)=>walk(child,[...node,index])));
   state.items=[...doc.body.children].map((el,index)=>walk(el,[index]));
   sidebar.update({path:'index.html',items:state.items});
  };
  const editor={isMounted:()=>true,captureHistoryHost:()=>{const model=state.model;return{isCurrent:()=>state.model===model};},prepareHistorySources:()=>{const model=state.model,version=state.version;return{isCurrent:()=>state.model===model&&state.version===version,dispose:()=>{}};},replaceActiveRange:(edit:any)=>{expectSource(edit);state.source=state.source.slice(0,edit.start)+edit.text+state.source.slice(edit.end);state.version++;update();},replaceActiveRanges:(edits:any[])=>{for(const edit of [...edits].sort((a,b)=>b.start-a.start)){expectSource(edit);state.source=state.source.slice(0,edit.start)+edit.text+state.source.slice(edit.end);}state.version++;update();},closeActiveEditGroup:()=>state.closed++};
  function expectSource(edit:any){if(state.source.slice(edit.start,edit.end)!==edit.expected)throw Error('stale range');}
  state.tools=createComponentTools({structureFields:true,site:()=>({components:{'project-card':templatePath},routes:{'/':'index.html'}}),edits:createGuardedEdits({...createMemoryWorkspace().workspace,scope:()=>String(state.revision)}),sources:()=>({'index.html':state.source,[templatePath]:state.template}),editor:()=>editor,preview:()=>({selectNode:(target:any)=>state.selected.push(target),selectAfterUpdate:()=>{}}),currentPath:()=>current,selection:()=>({path:'index.html',node:[0],tag:'project-card',text:'',reason:'click',selectors:[]}),openFile:async(path:string)=>{state.opened.push(path);current=path;return true;},announce:(value:string)=>state.notices.push(value),error:(error:any)=>{throw error;},images:()=>["media/suggested.png"],upload:async()=>{state.uploadCalls=(state.uploadCalls??0)+1;return await new Promise(resolve=>state.finishUpload=resolve);},links:()=>[{label:"About",value:"/about/"}],pageLabel:(path:string)=>path,panelHost:host,addStrip:(element:any)=>host.append(element),codeTitle:document.createElement('div'),previewPage:()=> 'index.html'});
  sidebar=createPageStructure(host,{announce:(value:string)=>state.notices.push(value),label:(item:any)=>({kind:item.tag==='project-card'?'Project card':item.tag,text:item.text,component:item.tag==='project-card'}),onSelect:(path:string,node:number[])=>state.selected.push({path,node}),onRowDrag:(_press:any,item:any)=>{state.movesTo.push({node:item.node,tag:item.tag});return undefined;},onMove:(path:string,item:any,direction:string)=>{state.moves.push({path,node:item.node,direction,tag:item.tag,same:item===state.items[0].children[1].children[1]});return "stayed";},componentSlots:(path:string,node:number[])=>state.tools.structure(path,node)});state.sidebar=sidebar;state.update=update;update();
 });
}

test('rich assigned wrappers retain authored rows, source order, selection and movement identity',async({page})=>{
 await harness(page);expect(await page.locator('[role=treeitem][data-node]').evaluateAll((rows:Element[])=>rows.map(row=>row.getAttribute('data-node')))).toEqual(['0','0.0','0.1','0.1.0','0.1.0.0','0.1.1','0.2','0.3','0.4']);await expect(page.locator('[role=treeitem][data-node="0.0"] .page-structure__slot-badge')).toHaveText('Title');await expect(page.getByRole('textbox',{name:'Title: Text',exact:true})).toHaveCount(0);await expect(page.locator('[role=treeitem][data-node="0.4"]')).toBeVisible();
 await page.locator('[role=treeitem][data-node="0.1"]').getByRole('button',{name:'Select Body',exact:true}).click();expect(await page.evaluate(()=>(window as any).slotHarness.selected.at(-1))).toEqual({path:"index.html",node:[0,1]});const wrapper=page.locator('[role=treeitem][data-node="0.1"]');await wrapper.click();expect(await page.evaluate(()=>(window as any).slotHarness.selected.at(-1))).toEqual({path:'index.html',node:[0,1]});const paragraph=page.locator('[role=treeitem][data-node="0.1.1"]');await paragraph.click();await paragraph.press('Alt+ArrowUp');expect(await page.evaluate(()=>(window as any).slotHarness.moves)).toEqual([{path:'index.html',node:[0,1,1],direction:'up',tag:'p',same:true}]);expect(await page.locator('[role=treeitem][aria-selected=true]').count()).toBe(1);
});
test('deep preview selection reveals folded rich rows and maintains one keyboard tab stop',async({page})=>{
 await harness(page);const wrapper=page.locator('[role=treeitem][data-node="0.1"]'),button=page.locator('[role=treeitem][data-node="0.1.0"]'),text=page.locator('[role=treeitem][data-node="0.1.0.0"]');await button.focus();await button.press('ArrowLeft');await wrapper.focus();await wrapper.press('ArrowLeft');await expect(text).toBeHidden();await page.evaluate(()=>(window as any).slotHarness.sidebar.select({path:'index.html',node:[0,1,0,0]}));await expect(text).toBeVisible();await expect(wrapper).toHaveAttribute('aria-expanded','true');await expect(button).toHaveAttribute('aria-expanded','true');await expect(text).toHaveAttribute('aria-selected','true');await expect(page.locator('[role=treeitem][aria-selected=true]')).toHaveCount(1);await expect(page.locator('[role=treeitem][tabindex="0"]')).toHaveCount(1);await expect(page.locator('[role=treeitem][data-node="0"]')).toHaveAttribute('aria-expanded','true');await expect(page.locator('.page-structure__inline')).toHaveCount(0);await text.focus();await text.press('ArrowLeft');await expect(button).toBeFocused();await button.press('ArrowDown');await expect(text).toBeFocused();await text.press('Enter');expect(await page.evaluate(()=>(window as any).slotHarness.selected.at(-1))).toEqual({path:'index.html',node:[0,1,0,0]});
});
test('source replacement removes stale rich rows without duplicating basic or unknown slots',async({page})=>{
 await harness(page);await page.evaluate(()=>{const s=(window as any).slotHarness;s.source=s.source.replace('<div slot="body" id="rich"><button><span>Act</span></button><p>Paragraph</p></div>','<div slot="body" id="rich"><p>New</p></div>');s.version++;s.update();});expect(await page.locator('[role=treeitem][data-node]').evaluateAll((rows:Element[])=>rows.map(row=>row.getAttribute('data-node')))).toEqual(['0','0.0','0.1','0.1.0','0.2','0.3','0.4']);await expect(page.locator('.page-structure__tree').getByText('Act',{exact:true})).toHaveCount(0);await expect(page.locator('[role=treeitem][data-node="0.0"]')).toHaveCount(1);await expect(page.getByRole('textbox',{name:'Title: Text',exact:true})).toHaveCount(0);await page.locator('[role=treeitem][data-node="0.0"]').press('F2');await expect(page.getByRole('textbox',{name:'Title: Text',exact:true})).toHaveCount(1);await expect(page.locator('[role=treeitem][data-slot="unknown"]')).toHaveCount(1);await expect(page.locator('[role=treeitem][data-node]')).toHaveCount(7);await expect(page.locator('[role=treeitem].page-structure__row--empty-slot')).toHaveCount(1);
});

test('showing link and image slots shows their fields and focuses the first',async({page})=>{
 await harness(page);for(const name of ['cta','image']){await page.evaluate(name=>{const s=(window as any).slotHarness;s.source='<project-card><span slot="title">Title</span></project-card>';s.template=`<section><div><slot name="${name}">${name==='cta'?'<a href="/fallback">Fallback</a>':'<img src="/fallback.png" alt="Fallback">'}</slot></div></section>`;s.version++;s.update();},name);await page.locator('.page-structure__row--empty-slot').hover();await page.getByRole('button',{name:name==='cta'?'Show Cta':'Show Image',exact:true}).click();const input=page.getByRole(name==='cta'?'textbox':'combobox',{name:name==='cta'?'Cta: Button text':'Image: Image',exact:true});await expect(input).toBeFocused();await expect(input).toBeVisible();await expect(page.getByRole('group',{name:name==='cta'?'Link':'Image',exact:true})).toBeVisible();}
});
test('canvas selection of a simple assigned slot reveals its native row without a form or caret theft',async({page})=>{
 await harness(page);const root=page.locator('[role=treeitem][data-node="0"]'),title=page.locator('[role=treeitem][data-node="0.0"]');await root.focus();await root.press('ArrowLeft');await expect(title).toBeHidden();await page.evaluate(()=>{const input=document.createElement('input');input.id='canvas-caret';document.body.append(input);input.focus();(window as any).slotHarness.sidebar.select({path:'index.html',node:[0,0]});});await expect(title).toBeVisible();await expect(title).toHaveAttribute('aria-selected','true');await expect(page.locator('.page-structure__inline')).toHaveCount(0);await expect(page.getByRole('textbox',{name:'Title: Text',exact:true})).toHaveCount(0);await expect(page.locator('#canvas-caret')).toBeFocused();await expect(root).toHaveAttribute('aria-expanded','true');
});
test('upload stale refusal is announced only after its asynchronous completion',async({page})=>{
 await harness(page);await page.evaluate(()=>{const s=(window as any).slotHarness;s.pendingUpload=s.tools.structure('index.html',[0]).openImageUpload('image').upload([new File(['image'],'image.png')]);});await page.waitForFunction(()=>{const s=(window as any).slotHarness;return s.uploadCalls===1&&typeof s.finishUpload==='function';});const before=await page.evaluate(()=>{const s=(window as any).slotHarness;s.source='<p>Replacement</p>';return [...s.notices];});expect(before).not.toContain('The instance changed while the image uploaded; it was not replaced.');const result=await page.evaluate(async()=>{const s=(window as any).slotHarness;s.finishUpload('/wrong.png');return{accepted:await s.pendingUpload,source:s.source,notices:s.notices};});expect(result.accepted).toBe(false);expect(result.source).toBe('<p>Replacement</p>');expect(result.notices).toContain('The instance changed while the image uploaded; it was not replaced.');
});
